### ISSUE TITLE
error when running train

### ISSUE THREAD

**Issue by DukeEnglish** [chrischute/squad#5]
hi, when i try to run the code, it happened:
enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0
could you pls help me? thanks a lot

**Comment by chrischute** [comment]
This is probably an out-of-memory error. See [this thread](https://stackoverflow.com/questions/56272981/pytorch-runtimeerror-enforce-fail-at-cpuallocator-cpp56-posix-memaligndata).
